import type { Metadata } from "next";
import Link from "next/link";
import RewindStories from "@/components/rewind/RewindStories";

export const metadata: Metadata = {
  title: "Selector · Rewind",
  description:
    "A year-in-listening story, for an invented listener or built in your browser from your own export: top artists, an artist race, listening age, taste clusters found by a fruit fly's olfactory circuit, and a listening archetype.",
};

export default function RewindPage() {
  return (
    <main>
      <div className="wrap rewind">
        <header className="hero rewind-hero">
          <p className="eyebrow">
            <Link href="/">Selector</Link> · Rewind
          </p>
          <h1>Three years of listening, as a story.</h1>
          <p className="lede">
            The listener here is invented: real catalog tracks, but every play, skip and timestamp was generated by{" "}
            <code>scripts/build_demo_assets.py</code>, the same sample export the demo offers. It runs through the exact pipeline a
            real export would. Every number comes from the warehouse; the taste clusters and hidden gems come from the fly
            brain&apos;s fingerprints. Each card says how much of the library it could see. Drop your own export on the home
            page first and the same cards are built from it, in this tab, with nothing uploaded.
          </p>
        </header>
        <RewindStories />
        <footer className="watch-foot">
          <p>
            Report schema 2.1, one JSON object per window, generated by{" "}
            <code>python -m selector.warehouse.wrapped --profile synthetic</code>. Your own is the same report, built in the
            browser by <code>web/lib/rewind-visitor.ts</code>. Cluster names are built from audio and mood features.{" "}
            <Link href="/">Explore your own export →</Link>
          </p>
        </footer>
      </div>
    </main>
  );
}
