import type { Metadata } from "next";
import Link from "next/link";
import Story from "@/components/wrapped/Story";

export const metadata: Metadata = {
  title: "Selector · Wrapped",
  description:
    "A Spotify-Wrapped-style story over four years of one listener's history: top artists, an artist race, listening age, taste clusters found by a fruit fly's olfactory circuit, and a listening archetype.",
};

export default function WrappedPage() {
  return (
    <main>
      <div className="wrap wrapped">
        <header className="hero wrapped-hero">
          <p className="eyebrow">
            <Link href="/">Selector</Link> · Wrapped
          </p>
          <h1>Four years of listening, as a story.</h1>
          <p className="lede">
            Built from the project author&apos;s own Spotify history. Every number comes from the warehouse; the taste clusters and
            hidden gems come from the fly brain&apos;s fingerprints. Each card says how much of the library it could see.
          </p>
        </header>
        <Story />
        <footer className="watch-foot">
          <p>
            Report schema 2.0, one JSON object per window, generated by <code>selector.warehouse.wrapped</code>. Cluster names come
            from features first; a language model only rewrites the headline.{" "}
            <Link href="/">Explore your own export →</Link>
          </p>
        </footer>
      </div>
    </main>
  );
}
